services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=Backend_Wakanda_Salud
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - "3307:3306"
    container_name: mysql-wakanda
    networks:
      - backend-network

  backend-wakanda-salud:
    build:
      context: ./  # Directorio del Dockerfile del microservicio
    ports:
      - "8080:8090"  # Mapea el puerto para el microservicio
    container_name: backend-wakanda-salud
    networks:
      - backend-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=default
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-wakanda:3306/Backend_Wakanda_Salud?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
    entrypoint: [
      "./wait-for-it.sh", "eureka-server:8761", "-t", "60", "--",
      "./wait-for-it.sh", "mysql-wakanda:3306", "-t", "60", "--",
      "java", "-jar", "/app/backend_wakanda_salud.jar"
    ]




volumes:
  mysql-data:

networks:
  backend-network:
    external: true
